### ISSUE TITLE
Interferes with Google Sheets

### ISSUE THREAD

**Issue by davidgilbertson** [craigfrancis/stop-animations#3]
When editing a cell in Google Sheets, `esc` normally exits the 'edit cell' mode. But with this extension installed, I have to press escape twice.

It would be great if the shortcut associated with this extension was a configurable command (I think you could still default to escape).

https://developer.chrome.com/docs/extensions/reference/commands/

**Comment by craigfrancis** [comment]
Hi David,

Thanks for the reminder, I've been meaning to do this for a while, and update to [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/). I'm unlikely to do it in the next couple of weeks (too many things on), but will try to do these changes soon.

As to the technical details, you are right about being able to use `esc` by default, but it needs to be done in a separate way... the current approach injects a JavaScript file into every page, and uses a 'keydown' event listener ([source](https://github.com/craigfrancis/stop-animations/blob/main/chrome/screenshot.js#L132)), whereas the "proper" way gets the browser to manage the shortcut, it has a few requirements (e.g. must include `Ctrl` or `Alt`), and when someone does set a shortcut, I need to communicate that to the content-script so it does not listen for `esc`.

**Comment by craigfrancis** [comment]
Hi David,

I've finally managed to add support for custom shortcuts.

If you go to "Extensions", make sure the Stop Animation extension is version 2.0 (or later)... and then use the 3 line menu in the top left, and choose "Keyboard shortcuts" (no idea why they have hidden it like that).
